name: phconvert
dependencies:
- freetype
- future
- hdf5
- libpng
- matplotlib
- numba
- numexpr
- numpy
- openssl
- pip
- pyparsing
- pyqt
- pytables
- python=3.6
- python-dateutil
- pytz
- qt
- readline
- setuptools
- sip
- six
- sqlite
- tk
- wheel
- xz
- zlib
- pip:
  - phconvert
