name: phconvert
dependencies:
- freetype
- future
- hdf5
- libpng
- matplotlib
- numexpr
- numpy
- openssl
- phconvert
- pip
- pyparsing
- pyqt
- pytables
- python
- python-dateutil
- pytz
- qt
- readline
- setuptools
- sip
- six
- sqlite
- tk
- wheel
- xz
- zlib
- pip:
  - tables==3.2.2

